# Generated by Django 4.2.2 on 2023-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="username",
            field=models.CharField(default="User", max_length=50),
        ),
    ]
